spring.application.name=jwtapp

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Janner12345@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Securiry config
//spring.security.user.name=janner
//spring.security.user.password=12345