spring.application.name=crud-persona

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/personasdb?useSSL=false
spring.datasource.username=root
spring.datasource.password=Janner12345@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
